version: "3.7"

services:
  desafio:
    image: postgres
    container_name: challenge_database
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=queries_challenge